create type "public"."ticket_priority" as enum ('Low', 'Medium', 'High', 'Critical');

create type "public"."ticket_status" as enum ('Open', 'Pending', 'Close');


  create table "public"."invite_tokens" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "company_id" bigint not null,
    "token" uuid default gen_random_uuid(),
    "used_at" timestamp with time zone,
    "role" public.app_role default 'customer_manager'::public.app_role
      );


alter table "public"."invite_tokens" enable row level security;


  create table "public"."tickets" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "company_id" bigint,
    "status" public.ticket_status default 'Open'::public.ticket_status,
    "priority" public.ticket_priority default 'Medium'::public.ticket_priority,
    "updated_at" timestamp without time zone default now(),
    "subject" text not null,
    "description" text,
    "customer_id" uuid not null
      );


alter table "public"."tickets" enable row level security;

CREATE UNIQUE INDEX invite_tokens_pkey ON public.invite_tokens USING btree (id);

CREATE UNIQUE INDEX tickets_pkey ON public.tickets USING btree (id);

alter table "public"."invite_tokens" add constraint "invite_tokens_pkey" PRIMARY KEY using index "invite_tokens_pkey";

alter table "public"."tickets" add constraint "tickets_pkey" PRIMARY KEY using index "tickets_pkey";

alter table "public"."invite_tokens" add constraint "invite_tokens_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE not valid;

alter table "public"."invite_tokens" validate constraint "invite_tokens_company_id_fkey";

alter table "public"."tickets" add constraint "tickets_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public.companies(id) not valid;

alter table "public"."tickets" validate constraint "tickets_company_id_fkey";

alter table "public"."tickets" add constraint "tickets_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES auth.users(id) not valid;

alter table "public"."tickets" validate constraint "tickets_customer_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_first_admin()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$declare
  admin_count int;
  user_name text;
  meta_company_id int8;
  invite_token uuid;
  user_role public.app_role;
begin
  user_name := COALESCE(
      new.raw_user_meta_data ->> 'name', 
      'User-' || RIGHT(new.id::text, 4)
    );

  meta_company_id := (new.raw_user_meta_data ->> 'company_id')::int8;

  invite_token := (new.raw_user_meta_data ->> 'invite_token')::uuid;

  if meta_company_id is not null then
    user_role := 'customer_manager';
  else
    select count(*) into admin_count from public.app_user where role = 'admin';

    if admin_count > 0 then
      user_role = 'agent';
    else
      user_role = 'admin';
    end if;
  end if;

  if invite_token is not null then
    update public.invite_tokens
    set used_at = now()
    where token = invite_token;
  end if;

  insert into public.app_user (id, name, role)
  values (
    new.id, 
    user_name, 
    user_role);
  return new;
end;$function$
;

grant delete on table "public"."invite_tokens" to "anon";

grant insert on table "public"."invite_tokens" to "anon";

grant references on table "public"."invite_tokens" to "anon";

grant select on table "public"."invite_tokens" to "anon";

grant trigger on table "public"."invite_tokens" to "anon";

grant truncate on table "public"."invite_tokens" to "anon";

grant update on table "public"."invite_tokens" to "anon";

grant delete on table "public"."invite_tokens" to "authenticated";

grant insert on table "public"."invite_tokens" to "authenticated";

grant references on table "public"."invite_tokens" to "authenticated";

grant select on table "public"."invite_tokens" to "authenticated";

grant trigger on table "public"."invite_tokens" to "authenticated";

grant truncate on table "public"."invite_tokens" to "authenticated";

grant update on table "public"."invite_tokens" to "authenticated";

grant delete on table "public"."invite_tokens" to "service_role";

grant insert on table "public"."invite_tokens" to "service_role";

grant references on table "public"."invite_tokens" to "service_role";

grant select on table "public"."invite_tokens" to "service_role";

grant trigger on table "public"."invite_tokens" to "service_role";

grant truncate on table "public"."invite_tokens" to "service_role";

grant update on table "public"."invite_tokens" to "service_role";

grant delete on table "public"."tickets" to "anon";

grant insert on table "public"."tickets" to "anon";

grant references on table "public"."tickets" to "anon";

grant select on table "public"."tickets" to "anon";

grant trigger on table "public"."tickets" to "anon";

grant truncate on table "public"."tickets" to "anon";

grant update on table "public"."tickets" to "anon";

grant delete on table "public"."tickets" to "authenticated";

grant insert on table "public"."tickets" to "authenticated";

grant references on table "public"."tickets" to "authenticated";

grant select on table "public"."tickets" to "authenticated";

grant trigger on table "public"."tickets" to "authenticated";

grant truncate on table "public"."tickets" to "authenticated";

grant update on table "public"."tickets" to "authenticated";

grant delete on table "public"."tickets" to "service_role";

grant insert on table "public"."tickets" to "service_role";

grant references on table "public"."tickets" to "service_role";

grant select on table "public"."tickets" to "service_role";

grant trigger on table "public"."tickets" to "service_role";

grant truncate on table "public"."tickets" to "service_role";

grant update on table "public"."tickets" to "service_role";


  create policy "Enable read access for all users"
  on "public"."companies"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."invite_tokens"
  as permissive
  for select
  to public
using (true);



  create policy "admin can interact with tokens"
  on "public"."invite_tokens"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.app_user
  WHERE ((app_user.id = auth.uid()) AND (app_user.role = 'admin'::public.app_role)))));



  create policy "admin can get all tickets"
  on "public"."tickets"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.app_user
  WHERE ((auth.uid() = app_user.id) AND (app_user.role = 'admin'::public.app_role)))));



