
  create table "public"."company_contacts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "email" character varying,
    "company_id" bigint not null,
    "name" text not null
      );


alter table "public"."company_contacts" enable row level security;


  create table "public"."messages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "sender_id" uuid,
    "updated_at" timestamp with time zone default now(),
    "ticket_id" bigint,
    "contact_id" bigint
      );


alter table "public"."messages" enable row level security;

alter table "public"."tickets" add column "contact_id" bigint;

CREATE UNIQUE INDEX company_contacts_pkey ON public.company_contacts USING btree (id);

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

alter table "public"."company_contacts" add constraint "company_contacts_pkey" PRIMARY KEY using index "company_contacts_pkey";

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."company_contacts" add constraint "company_contacts_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE not valid;

alter table "public"."company_contacts" validate constraint "company_contacts_company_id_fkey";

alter table "public"."messages" add constraint "messages_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES public.company_contacts(id) ON DELETE SET NULL not valid;

alter table "public"."messages" validate constraint "messages_contact_id_fkey";

alter table "public"."messages" add constraint "messages_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."messages" validate constraint "messages_sender_id_fkey";

alter table "public"."messages" add constraint "messages_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES public.tickets(id) ON DELETE CASCADE not valid;

alter table "public"."messages" validate constraint "messages_ticket_id_fkey";

alter table "public"."tickets" add constraint "tickets_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES public.company_contacts(id) ON DELETE SET NULL not valid;

alter table "public"."tickets" validate constraint "tickets_contact_id_fkey";

alter table "public"."tickets" add constraint "tickets_customer_id_fkey1" FOREIGN KEY (customer_id) REFERENCES public.app_user(id) ON DELETE SET NULL not valid;

alter table "public"."tickets" validate constraint "tickets_customer_id_fkey1";

create or replace view "public"."agent_details" as  SELECT COALESCE(au.id, '00000000-0000-0000-0000-000000000000'::uuid) AS id,
    u.email,
    au.name,
    COALESCE(json_agg(json_build_object('id', c.id, 'name', c.name)) FILTER (WHERE (c.id IS NOT NULL)), '[]'::json) AS companies
   FROM (((public.app_user au
     JOIN auth.users u ON ((au.id = u.id)))
     LEFT JOIN public.user_companies uc ON ((au.id = uc.user_id)))
     LEFT JOIN public.companies c ON ((uc.company_id = c.id)))
  WHERE (au.role = 'agent'::public.app_role)
  GROUP BY au.id, u.email, au.name;


grant delete on table "public"."company_contacts" to "anon";

grant insert on table "public"."company_contacts" to "anon";

grant references on table "public"."company_contacts" to "anon";

grant select on table "public"."company_contacts" to "anon";

grant trigger on table "public"."company_contacts" to "anon";

grant truncate on table "public"."company_contacts" to "anon";

grant update on table "public"."company_contacts" to "anon";

grant delete on table "public"."company_contacts" to "authenticated";

grant insert on table "public"."company_contacts" to "authenticated";

grant references on table "public"."company_contacts" to "authenticated";

grant select on table "public"."company_contacts" to "authenticated";

grant trigger on table "public"."company_contacts" to "authenticated";

grant truncate on table "public"."company_contacts" to "authenticated";

grant update on table "public"."company_contacts" to "authenticated";

grant delete on table "public"."company_contacts" to "service_role";

grant insert on table "public"."company_contacts" to "service_role";

grant references on table "public"."company_contacts" to "service_role";

grant select on table "public"."company_contacts" to "service_role";

grant trigger on table "public"."company_contacts" to "service_role";

grant truncate on table "public"."company_contacts" to "service_role";

grant update on table "public"."company_contacts" to "service_role";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";


  create policy "customer manager can manage their contacts"
  on "public"."company_contacts"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.user_companies
  WHERE ((user_companies.company_id = company_contacts.company_id) AND (user_companies.user_id = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM public.user_companies
  WHERE ((user_companies.company_id = company_contacts.company_id) AND (user_companies.user_id = auth.uid())))));



  create policy "Admin can see all messages"
  on "public"."messages"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.app_user
  WHERE ((auth.uid() = app_user.id) AND (app_user.role = 'admin'::public.app_role)))))
with check ((EXISTS ( SELECT 1
   FROM public.app_user
  WHERE ((auth.uid() = app_user.id) AND (app_user.role = 'admin'::public.app_role)))));



  create policy "customer_manager can see and insert messages"
  on "public"."messages"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.tickets t
     JOIN public.user_companies uc ON ((t.company_id = uc.company_id)))
  WHERE ((t.id = messages.ticket_id) AND (uc.user_id = auth.uid())))))
with check (((EXISTS ( SELECT 1
   FROM (public.tickets t
     JOIN public.user_companies uc ON ((t.company_id = uc.company_id)))
  WHERE ((t.id = messages.ticket_id) AND (uc.user_id = auth.uid())))) AND (sender_id = auth.uid())));



